// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Block: typeof import('substrat')['Block']
    Center: typeof import('substrat')['Center']
    DarkModeButton: typeof import('substrat')['DarkModeButton']
    DropdownButton: typeof import('substrat')['DropdownButton']
    Feldspar: typeof import('substrat')['Feldspar']
    Footer: typeof import('substrat')['Footer']
    Frame: typeof import('substrat')['Frame']
    Grid: typeof import('substrat')['Grid']
    HUD: typeof import('substrat')['HUD']
    ImgSideCar: typeof import('substrat')['ImgSideCar']
    Link: typeof import('substrat')['Link']
    LinkButton: typeof import('substrat')['LinkButton']
    List: typeof import('substrat')['List']
    Navbar: typeof import('substrat')['Navbar']
    Pyroxene: typeof import('substrat')['Pyroxene']
    Reel: typeof import('substrat')['Reel']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('substrat')['Rule']
    Sidebar: typeof import('substrat')['Sidebar']
    SideCar: typeof import('substrat')['SideCar']
    Stagger: typeof import('substrat')['Stagger']
    SubButton: typeof import('substrat')['SubButton']
    SubSection: typeof import('substrat')['SubSection']
    SubSectionList: typeof import('substrat')['SubSectionList']
    Sunstone: typeof import('substrat')['Sunstone']
    TestNav: typeof import('./components/TestNav.vue')['default']
    Trifold: typeof import('substrat')['Trifold']
  }
}
