// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Block: typeof import('@agency-kit/substrat')['Block']
    Center: typeof import('@agency-kit/substrat')['Center']
    DarkModeButton: typeof import('@agency-kit/substrat')['DarkModeButton']
    DropdownButton: typeof import('@agency-kit/substrat')['DropdownButton']
    Feldspar: typeof import('@agency-kit/substrat')['Feldspar']
    Footer: typeof import('@agency-kit/substrat')['Footer']
    FormInput: typeof import('@agency-kit/substrat')['FormInput']
    FormMessage: typeof import('@agency-kit/substrat')['FormMessage']
    Grid: typeof import('@agency-kit/substrat')['Grid']
    HUD: typeof import('@agency-kit/substrat')['HUD']
    Link: typeof import('@agency-kit/substrat')['Link']
    LinkButton: typeof import('@agency-kit/substrat')['LinkButton']
    Navbar: typeof import('@agency-kit/substrat')['Navbar']
    NetlifyForm: typeof import('@agency-kit/substrat')['NetlifyForm']
    Pyroxene: typeof import('substrat')['Pyroxene']
    ReelNav: typeof import('@agency-kit/substrat')['ReelNav']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('@agency-kit/substrat')['Rule']
    SubNav: typeof import('@agency-kit/substrat')['SubNav']
    SubSection: typeof import('@agency-kit/substrat')['SubSection']
    Sunstone: typeof import('substrat')['Sunstone']
    TestNav: typeof import('./components/TestNav.vue')['default']
  }
}
