// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Block: typeof import('./components/atoms/Block.vue')['default']
    Card: typeof import('./components/atoms/Card.vue')['default']
    Center: typeof import('./components/atoms/Center.vue')['default']
    Chalcedony: typeof import('./layouts/Chalcedony.vue')['default']
    Cluster: typeof import('./components/atoms/Cluster.vue')['default']
    Cover: typeof import('./components/atoms/Cover.vue')['default']
    DarkModeButton: typeof import('./components/molecules/DarkModeButton.vue')['default']
    DoubleCluster: typeof import('./components/atoms/DoubleCluster.vue')['default']
    Feldspar: typeof import('./layouts/Feldspar.vue')['default']
    Fluorite: typeof import('./layouts/Fluorite.vue')['default']
    Footer: typeof import('./components/molecules/Footer.vue')['default']
    FormInput: typeof import('./components/atoms/forms/FormInput.vue')['default']
    FormMessage: typeof import('./components/atoms/forms/FormMessage.vue')['default']
    Frame: typeof import('./components/atoms/Frame.vue')['default']
    Grid: typeof import('./components/atoms/Grid.vue')['default']
    GridItem: typeof import('./components/atoms/GridItem.vue')['default']
    HyperFooter: typeof import('./components/molecules/HyperFooter.vue')['default']
    HyperNav: typeof import('./components/molecules/HyperNav.vue')['default']
    ImageHero: typeof import('./components/atoms/ImageHero.vue')['default']
    ImgSideCar: typeof import('./components/molecules/ImgSideCar.vue')['default']
    Labradorite: typeof import('./layouts/Labradorite.vue')['default']
    Modal: typeof import('./components/atoms/Modal.vue')['default']
    Navbar: typeof import('./components/molecules/Navbar.vue')['default']
    NetlifyForm: typeof import('./components/atoms/forms/NetlifyForm.vue')['default']
    Opal: typeof import('./layouts/Opal.vue')['default']
    Pyroxene: typeof import('./layouts/Pyroxene.vue')['default']
    Reel: typeof import('./components/atoms/Reel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('./components/atoms/Rule.vue')['default']
    SampleContactForm: typeof import('./components/atoms/forms/SampleContactForm.vue')['default']
    Sidebar: typeof import('./components/molecules/Sidebar.vue')['default']
    SideCar: typeof import('./components/atoms/SideCar.vue')['default']
    SubButton: typeof import('./components/atoms/SubButton.vue')['default']
    SubSection: typeof import('./components/atoms/SubSection.vue')['default']
    SubSectionList: typeof import('./components/atoms/SubSectionList.vue')['default']
    ThemePickButton: typeof import('./components/molecules/ThemePickButton.vue')['default']
    Trifold: typeof import('./components/molecules/Trifold.vue')['default']
  }
}
