// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./components/atoms/Card.vue')['default']
    Center: typeof import('./components/atoms/Center.vue')['default']
    Cluster: typeof import('./components/atoms/Cluster.vue')['default']
    DoubleCluster: typeof import('./components/atoms/DoubleCluster.vue')['default']
    Footer: typeof import('./components/molecules/Footer.vue')['default']
    Frame: typeof import('./components/atoms/Frame.vue')['default']
    Grid: typeof import('./components/atoms/Grid.vue')['default']
    GridItem: typeof import('./components/atoms/GridItem.vue')['default']
    ImageHero: typeof import('./components/atoms/ImageHero.vue')['default']
    Navbar: typeof import('./components/molecules/Navbar.vue')['default']
    Sidebar: typeof import('./components/atoms/Sidebar.vue')['default']
    SubSection: typeof import('./components/atoms/SubSection.vue')['default']
    SubSectionList: typeof import('./components/atoms/SubSectionList.vue')['default']
  }
}
