// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Block: typeof import('./components/atoms/Block.vue')['default']
    Center: typeof import('./components/atoms/Center.vue')['default']
    Cluster: typeof import('./components/atoms/Cluster.vue')['default']
    ClusterNav: typeof import('./components/molecules/Navigation/ClusterNav.vue')['default']
    DarkModeButton: typeof import('./components/molecules/Buttons/DarkModeButton.vue')['default']
    DateInput: typeof import('./components/atoms/forms/DateInput.vue')['default']
    DoubleCluster: typeof import('./components/atoms/DoubleCluster.vue')['default']
    Dropdown: typeof import('./components/atoms/Dropdown.vue')['default']
    DropdownButton: typeof import('./components/molecules/Buttons/DropdownButton.vue')['default']
    Feldspar: typeof import('./layouts/Feldspar.vue')['default']
    FileUpload: typeof import('./components/atoms/forms/FileUpload.vue')['default']
    Footer: typeof import('./components/molecules/Footer.vue')['default']
    FormInput: typeof import('./components/atoms/forms/FormInput.vue')['default']
    FormMessage: typeof import('./components/atoms/forms/FormMessage.vue')['default']
    Frame: typeof import('./components/atoms/Frame.vue')['default']
    Grid: typeof import('./components/atoms/Grid.vue')['default']
    GridEntity: typeof import('./components/atoms/GridEntity.vue')['default']
    GridItem: typeof import('./components/atoms/GridItem.vue')['default']
    HUD: typeof import('./components/molecules/HUD.vue')['default']
    ImageHero: typeof import('./components/atoms/ImageHero.vue')['default']
    ImgSideCar: typeof import('./components/molecules/ImgSideCar.vue')['default']
    Lazy: typeof import('./components/atoms/Lazy.vue')['default']
    Link: typeof import('./components/atoms/Link.vue')['default']
    LinkButton: typeof import('./components/atoms/LinkButton.vue')['default']
    List: typeof import('./components/atoms/List.vue')['default']
    NetlifyForm: typeof import('./components/atoms/forms/NetlifyForm.vue')['default']
    Reel: typeof import('./components/atoms/Reel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('./components/atoms/Rule.vue')['default']
    SideCar: typeof import('./components/atoms/SideCar.vue')['default']
    SimpleContactForm: typeof import('./components/atoms/forms/SimpleContactForm.vue')['default']
    SubButton: typeof import('./components/atoms/SubButton.vue')['default']
    SubNav: typeof import('./components/molecules/Navigation/SubNav.vue')['default']
    SubSection: typeof import('./components/atoms/SubSection.vue')['default']
    SubSectionList: typeof import('./components/atoms/SubSectionList.vue')['default']
    Sunstone: typeof import('./layouts/Sunstone.vue')['default']
  }
}
